FROM yhnw/openwrt-image-generator:base

ENV GENERATOR_URL "http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/lede-imagebuilder-ar71xx-generic.Linux-x86_64.tar.bz2"
ENV GENERATOR_SUFFIX .tar.bz2

RUN sudo -iu openwrt wget --progress=dot:giga $GENERATOR_URL &&\
    sudo -iu openwrt tar xjf "$(basename $GENERATOR_URL)" &&\
    sudo -iu openwrt rm "$(basename $GENERATOR_URL)" &&\
    sudo -iu openwrt mv "$(basename $GENERATOR_URL $GENERATOR_SUFFIX)" generator
